/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.everis.archivado.invoice.api;

import com.everis.archivado.invoice.model.ChargeItems;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@Api(value = "invoices", description = "the invoices API")
public interface InvoicesApi {

    @ApiOperation(value = "get charges by invoice id", nickname = "appliedCharges", notes = "", response = ChargeItems.class, tags={ "invoices", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = ChargeItems.class) })
    @RequestMapping(value = "/invoices/{invoiceId}/appliedCharges",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<ChargeItems> appliedCharges(@ApiParam(value = "Id of the invoice to fetch",required=true) @PathVariable("invoiceId") String invoiceId) throws Exception;

}
